name: Lint VPC Module
on:
  pull_request:
    branches:
      - main
    paths:
      - modules/vpc/**
      - .github/workflows/vpc-module-lint.yaml
  workflow_dispatch:
    inputs:
      terraform_files_path:
        required: true
        description: Path to the module to validate
        type: string
        default: "modules/vpc"
      enable_terraform_docs_check:
        required: false
        description: Enable terraform-docs check , applicable for modules only.
        type: boolean
        default: true


permissions:
  pull-requests: write
  contents: read

concurrency:
  group: vpc-module-lint
  cancel-in-progress: true

jobs:
    checkout:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
    validate-vpc-module-config:
      uses: ./.github/workflows/lint.yaml
      needs: checkout
      with:
        terraform_files_path: "modules/vpc"
        enable_terraform_docs_check: true

